Added SCS file lessons, markup to HTML file and changes to file pakag…
uanvi/final-project-english-excellence pull request #18
Opened 2024-10-03 09:49 UTC by Vitalii1983-vr

…e.json (according to the instructions, your email address)

2024-10-03 16:57 UTC, uanvi requested changes

2024-10-03 16:57 UTC, uanvi commented on src/css/lesson.css
> +:root {
need to delete this
all already defined in base.css 
pls use existing common params

2024-10-03 16:57 UTC, uanvi commented on src/partials/lessons.html
>  <section class="lessons">
add class section here

2024-10-03 16:57 UTC, uanvi commented on src/partials/lessons.html
> +  <div class="lessons-container">
add class container here

2024-10-03 16:57 UTC, uanvi commented on src/css/lesson.css
> +}
to avoid code duplication
just use common class underline-effect  (you can find it in effect.css)

2024-10-03 16:57 UTC, uanvi commented on src/css/lesson.css
> +/* Контейнер для планів */
pls do according to design

for desktop show all three plans - it ok
for taablet you shoul have 2 columns (2 plans in first row + 1 on onother)
for mobile you should have all plans in 1 column

2024-10-03 19:28 UTC, Vitalii1983-vr commented on src/css/lesson.css
> +}
Тоді мені треба і в CSS видалити ці параметри? І взагалі у моїй папці стилів не прописувати значення цього стилю?

2024-10-03 19:49 UTC, uanvi commented on src/css/lesson.css
> +}
саме так

2024-10-03 19:50 UTC, Vitalii1983-vr commented on src/css/lesson.css
> +}
Зрозумів. Дякую

2024-10-04 10:15 UTC, uanvi approved these changes

2024-10-04 10:15 UTC, merged